version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo 'Running unit tests'
      - cd HelloWorldFunction
      - mvn install
      - mvn test
